### ISSUE TITLE
105 set on firmware 235 issue

### ISSUE THREAD

**Issue by MatGriffin** [nschum/homebridge-twinkly#1]
I have 3 sets of gen 1 twinkly lights, 2 x175 and 1x105

Both 175 sets work fine, the 105 set will turn off but fails to turn back on, using terminal to try to turn on shows this error:

`twinkly --ip 192.168.1.171 --mode on
Authentication…
POST http://192.168.1.171/xled/v1/login
{ authentication_token: 'uOSr5nIIw8A=',
  authentication_token_expires_in: 14400,
  'challenge-response': '4805414b7bc9bda2284e97bee782af200a1f4ea5',
  code: 1000 }
POST http://192.168.1.171/xled/v1/verify
{ code: 1000 }
Authentication successful
GET http://192.168.1.171/xled/v1/gestalt
{ product_name: 'Twinkly',
  product_version: '2',
  hardware_version: '6',
  flash_size: 16,
  led_type: 5,
  led_version: '1',
  product_code: 'TW105SEUM06',
  device_name: 'Twinkly 105',
  uptime: '1339258',
  rssi: -66,
  hw_id: '0023b7dd',
  mac: 'a0:20:a6:23:b7:dd',
  uuid: '00000000-0000-0000-0000-000000000000',
  max_supported_led: 224,
  base_leds_number: 105,
  number_of_led: 105,
  led_profile: 'RGB',
  frame_rate: 25,
  movie_capacity: 719,
  copyright: 'LEDWORKS 2017',
  code: 1000 }
(node:30517) UnhandledPromiseRejectionWarning: unknown color format undefined
(node:30517) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:30517) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by MatGriffin** [comment]
ok simple fix reapply an effect like rainbow and now it works

**Comment by nschum** [comment]
The command line tool for turning on was broken (when not specifying a color). Should be fixed after #3.
