### ISSUE TITLE
mode = 'effect'

### ISSUE THREAD

**Issue by vanHoesel** [nschum/homebridge-twinkly#11]
The twinkly receiver-box can be put in one off 5 different effects, by pressing the button repeatedly. Next to the effects, there is also 'movie' that one will click through when pressing the button.

The on/brightness methods assume the current mode is 'movie'. That might be very well the case.

The annoyance is that after a Twinkly RESET, that movie is 'empty'. This leads to an undesired side effect: the "on" command does not seem to work and the get_mode responds with "off".

Please mention in the documentation with some sort of warning in the device setup phase: one need to select an effect AND apply it from the app, for homebridge-twinkly to switch it back on again.

Or even better, somehow retain the current mode before a "off" command, and use that when switching back "on". Maybe, also do a fall back if set_mode('movie') keeps returning "off", and switch to 'effect'.

**Comment by nschum** [comment]
Thank you for these insights. I've implemented the fallback so it always turns on. This also means support for the playlists they've introduced recently. This is now consistent with how the on/off switch in the Twinkly app works.

(I'm not going to remember the current mode when turning off, because that might leave things in an outdated state if the app is used to modify the movies.)

**Comment by vanHoesel** [comment]
Awesome!!!

I would have responded earlier, if Mail didn't mark the notification as spam.

Love reading up your code changes

**Comment by vanHoesel** [comment]
> Thank you for these insights. I've implemented the fallback so it always turns on. This also means support for the playlists they've introduced recently. This is now consistent with how the on/off switch in the Twinkly app works.
> 
> I'm not going to remember the current mode when turning off, because that might leave things in an outdated state if the app is used to modify the movies.

persisting state before switching off would be tricky indeed, I don't blame you
