### ISSUE TITLE
No response

### ISSUE THREAD

**Issue by h0mesmart** [nschum/homebridge-twinkly#4]
Hello,

I've installed the plugin as is on homebridge v. 1.2.3  node v. v12.19.0, iOS 14.1 and I get a no response as status in Home app. When I hit the tile to turn on the led strip it's shows ON, but the led do not light up. And it's shows no response still. 
When I force touch the tile to change the brightness, the led strip light up but still show as no response. 

Please help. 

Thank you

**Comment by WendelFelius** [comment]
Same!

**Comment by Liniment** [comment]
For me its working in Homebridge when I click on it or use the command line. But it shows up as No Response in the Home app.

**Comment by staxmood** [comment]
I can confirm that the issues resolve around the code being written for the lights before the light required network authentication. Specifically the screenshot below shows there is an error within authorization and the documentation doesn't mention it.

![image](https://user-images.githubusercontent.com/55040826/99139604-47bb8e80-2608-11eb-901a-be8148ffdfdf.png)

**Comment by jqnatividad** [comment]
I got around this problem by installing xled (https://pypi.org/project/xled/) and then using the Script2 homebridge plugin (https://www.npmjs.com/package/homebridge-script2) to create a switch that calls xled:

```
{
    "name": "Tree Lights",
    "fileState": "/var/switchstates/treelights",
    "on": "/home/hoobs/.local/bin/xled --hostname 192.168.5.88 on; touch /var/switchstates/treelights",
    "off": "/home/hoobs/.local/bin/xled --hostname 192.168.5.88 off; rm /var/switchstates/treelights",
    "accessory": "Script2",
    "unique_serial": "12345treelights"
}
```

**Comment by cardentey** [comment]
Same! :-(

**Comment by GunnarBaldursson** [comment]
Same. Also since I installed the plugin. My ATV 4k acting as a homekit hub is losing connection and not responding with an interval of 1-2 hours. I have to open the home app to get response from the hub.

**Comment by WendelFelius** [comment]
Fixed it by using cmdSwitch2:

`{
            "platform": "cmdSwitch2",
            "name": "CMD Switch",
            "switches": [ {
                    "name": "Twinkly",
                    "on_cmd": "twinkly --ip 192.168.x.xxx --mode movie",
                    "off_cmd": "twinkly --ip 192.168.x.xxx --mode off"
                }]
}`

Although I can't set the brightness, at least it's responding all the time.

**Comment by CyrilPeponnet** [comment]
Turning `allowBrightnessControl` to false fixed the issue for me. So might be related to the way the current brightness level is retrieved.

**Comment by Raiden38** [comment]
I can confirm that. When I put the config below, all devices on the home bridge show No Response! However, as CyrilPeponnet mentionned, if I set the allowBrightnessControl to false, then it looks ok. Can it be fixed quickly (as it's christmas season!) 👍 

        {
            "accessory": "Twinkly",
            "name": "Bébé Sapin",
            "ip": "192.168.0.108",
            "allowBrightnessControl": true
        },
        {
            "accessory": "Twinkly",
            "name": "Sapin",
            "ip": "192.168.0.35",
            "allowBrightnessControl": true
        }

**Comment by Raiden38** [comment]
Also want to mention that I have 2 Twinkly, and if one of them has a wrong IP address, both of them won't be working in HomeKit.

**Comment by GunnarBaldursson** [comment]
I'm not shure what happened. I had to uninstall this plugin because it made everything unresponsive.

**Comment by danielepenguin** [comment]
Same for me. Turning allowBrightnessControl to False did not fix the issue

**Comment by coderandgentleman** [comment]
Same issue here.

**Comment by nschum** [comment]
Hey, everybody. Unfortunately I generally only have time to work on this during the holiday season.
But I just unpacked the decorations and will probably have some time to tinker.

I wasn't able to reproduce the problem so far, but @dfuchslin says he fixed it here: #8 
I released version 0.2.2, so please report back if you still see the issue.

**Comment by nschum** [comment]
I've released another version with much better recovery from connection errors. It should also reduce the problems with other strips when one strip is unreachable. Please let me know if it improves.

**Comment by Raiden38** [comment]
Looks good for me! Resolved all my issues! Thanks so much! :)

**Comment by Raiden38** [comment]
Sorry to say but this new update broke it again. Everything was working perfectly with your fix but today's update returned the no response issue :(. Actually, when you reboot homebridge everything works but after a few minutes, everything crashes and I get no response..

**Comment by nschum** [comment]
> Sorry to say but this new update broke it again. Everything was working perfectly with your fix but today's update returned the no response issue

It seems more likely that the effect is just random and was never fixed at all.
Could you please post logs of a time when you had no response?

**Comment by Raiden38** [comment]
You are totally right. I woke up this morning and I have all no response.. However, I don't see any special error messages in my log. These are the logs related to twinkly:
`[09/12/2020, 07:11:54] [Bébé Sapin] GET http://192.168.0.108/xled/v1/led/out/brightness
[09/12/2020, 07:11:55] [Bébé Sapin] { value: 100, code: 1000 }
[09/12/2020, 07:11:55] [Bébé Sapin] GET http://192.168.0.108/xled/v1/led/mode
[09/12/2020, 07:11:55] [Bébé Sapin] { mode: 'off', code: 1000 }`

**Comment by Raiden38** [comment]
Hi @nschum! Just FYI, just like before I have set "allowBrightnessControl": false and everything worked again, just like in the beginning. Sorry that your fix did not worked, hope you will find something else! Here is the last log I have, and thanks for your help! :)

[09/12/2020, 16:59:09] [Bébé Sapin] Authentication…
[09/12/2020, 16:59:09] [Bébé Sapin] POST http://192.168.0.108/xled/v1/login
[09/12/2020, 16:59:09] [Bébé Sapin] {"challenge":"00000000000000000000000000000000000000000000"}
[09/12/2020, 16:59:09] [Sapin] {
  authentication_token: 'lmzQ8/oVwjA=',
  authentication_token_expires_in: 14400,
  'challenge-response': '398b524b354149cc093ed7572d467cbdf13e8385',
  code: 1000
}
[09/12/2020, 16:59:09] [Sapin] POST http://192.168.0.30/xled/v1/verify
[09/12/2020, 16:59:09] [Sapin] {"challenge-response":"398b524b354149cc093ed7572d467cbdf13e8385"}
[09/12/2020, 16:59:09] [Bébé Sapin] {
  authentication_token: 'ZHgVMHWA3h8=',
  authentication_token_expires_in: 14400,
  'challenge-response': 'df87de11e9a09a07b88374ddea52dc055dff4790',
  code: 1000}
[09/12/2020, 16:59:09] [Bébé Sapin] POST http://192.168.0.108/xled/v1/verify
[09/12/2020, 16:59:09] [Bébé Sapin] {"challenge-response":"df87de11e9a09a07b88374ddea52dc055dff4790"}
[09/12/2020, 16:59:09] [Bébé Sapin] { code: 1000 }
[09/12/2020, 16:59:09] [Bébé Sapin] Authentication successful
[09/12/2020, 16:59:09] [Bébé Sapin] GET http://192.168.0.108/xled/v1/led/mode
[09/12/2020, 16:59:09] [Sapin] { code: 1000 }
[09/12/2020, 16:59:09] [Sapin] Authentication successful
[09/12/2020, 16:59:09] [Sapin] GET http://192.168.0.30/xled/v1/led/mode
[09/12/2020, 16:59:09] [Bébé Sapin] { mode: 'movie', code: 1000 }
[09/12/2020, 16:59:09] [Sapin] { mode: 'movie', shop_mode: 0, code: 1000 }
[09/12/2020, 17:00:48] [Bébé Sapin] GET http://192.168.0.108/xled/v1/led/mode
[09/12/2020, 17:00:48] [Sapin] GET http://192.168.0.30/xled/v1/led/mode
[09/12/2020, 17:00:48] [Bébé Sapin] { mode: 'movie', code: 1000 }
[09/12/2020, 17:00:49] [Sapin] { mode: 'movie', shop_mode: 0, code: 1000 }
[09/12/2020, 17:00:53] [Bébé Sapin] GET http://192.168.0.108/xled/v1/led/mode
[09/12/2020, 17:00:53] [Sapin] GET http://192.168.0.30/xled/v1/led/mode
[09/12/2020, 17:00:54] [Bébé Sapin] { mode: 'movie', code: 1000 }
[09/12/2020, 17:00:54] [Sapin] { mode: 'movie', shop_mode: 0, code: 1000 }

**Comment by NateUT99** [comment]
I am having the exact same issue as what was reported in #9 ; turning on the lights in HomeKit does not do anything until I adjust the brightness and then the lights come on. I have tried setting the brightness control to false, but then i am unable to get the lights to output anything. Latest version of HB, the plugin, and firmware.

**Comment by iDreamsX** [comment]
> I am having the exact same issue as what was reported in #9 ; turning on the lights in HomeKit does not do anything until I adjust the brightness and then the lights come on. I have tried setting the brightness control to false, but then i am unable to get the lights to output anything. Latest version of HB, the plugin, and firmware... brand new lights just out of the box. 

Hello, for my part, the problem was just a mistake on my part. An effect must be applied to those available, and this works. That is very strange, but now it works. I'm also staying in 0.2.2, here 0.3.0 put the garland in "not answer"

**Comment by NateUT99** [comment]
> > I am having the exact same issue as what was reported in #9 ; turning on the lights in HomeKit does not do anything until I adjust the brightness and then the lights come on. I have tried setting the brightness control to false, but then i am unable to get the lights to output anything. Latest version of HB, the plugin, and firmware... brand new lights just out of the box.
> 
> Hello, for my part, the problem was just a mistake on my part. An effect must be applied to those available, and this works. That is very strange, but now it works. I'm also staying in 0.2.2, here 0.3.0 put the garland in "not answer"

Thanks, I miss missing the "apply" part as well. Everything seems to be working; I configured the brightness control to "true" so I'll see if I end up with a similar issue.

**Comment by nschum** [comment]
@Raiden38 These logs seem to be of the time of start-up. Did you try to do anything that failed during that time period?

Also, could you check if removing one of the lights makes a difference?

**Comment by nschum** [comment]
I've spent an hour repeatedly unplugging my lights and released another update. Hope it improves things. :)

**Comment by tdecroyere** [comment]
It seems that the latest version 0.3.3 was not working anymore with my lights. I have Version1 twinkly lights and it was trying to POST with the "playlist" mode.

Reverting back to 0.3.2 fixed the issue because it uses now the "movie" mode.

**Comment by andyblac** [comment]
> It seems that the latest version 0.3.3 was not working anymore with my lights. I have Version1 twinkly lights and it was trying to POST with the "playlist" mode.
> 
> Reverting back to 0.3.2 fixed the issue because it uses now the "movie" mode.

same here. ver1 and 0.3.2 working, 0.3.3 not.

**Comment by NateUT99** [comment]
.3.3 with playlist mode seems to be working better with my v2 lights; will continue to monitor.

**Comment by nschum** [comment]
See for #13 for the issue with 0.3.3. Apparently some lights return different return codes than mine. 🤷 0.3.4 should fix it.
Anyway, since there are no more reports of "no response", I'll close this.
