### ISSUE TITLE
UI for configuration

### ISSUE THREAD

**Issue by PrimaryInc** [nschum/homebridge-twinkly#6]
Hi @nschum,

Would it be possible for you to add the condig to the HomeBridge UI?
Also are you looking at implementing more feature as in the twinkly app?

Do you have any more config examples that the one in "example", i get power on and of, and brightness in homebridge.
But no fuction like change lights and so on.

**Comment by nschum** [comment]
Yes, but it depends on my free time. (PRs are always welcome …)

All implemented features will be in the README. I hope to do some work on colors, but HomeKit isn't really designed for handling multiple colors.

**Comment by PrimaryInc** [comment]
Hi @nschum,

I know that a lot of fuctions in HomeKit is missing, hopefully it will be developet over time. 
Thanks for you reply.

As I said, it would also be very helpfull implementing the HomeBridge WEB UI intregration for you plugin.
It would help people as my self that is not competent in json getting thigs working.

**Comment by rcoletti116** [comment]
> Yes, but it depends on my free time. (PRs are always welcome …)
> 
> All implemented features will be in the README. I hope to do some work on colors, but HomeKit isn't really designed for handling multiple colors.

Maybe not colors, but perhaps you could load different effects using Input Source.

**Comment by nschum** [comment]
> Maybe not colors, but perhaps you could load different effects using Input Source.

Yes. The big question is how to configure the effects, though. Ideally it should be possible to download effects created by the official app. I'll be playing toying around with it in the next few weeks.

Anyway, looks like the configuration was much easier to add than I thought. I've just released it.

**Comment by PrimaryInc** [comment]
Perfekt thank you!! 👍
