### ISSUE TITLE
error not found

### ISSUE THREAD

**Issue by bmpreston** [nschum/homebridge-twinkly#7]
Any assistance on the Config.json?

[11/30/2020, 12:03:04 AM] [Christmas Tree] Error: getaddrinfo ENOTFOUND undefined
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:66:26) {
  errno: 'ENOTFOUND',
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'undefined'

**Comment by PrimaryInc** [comment]
Hi @bmpreston,

Question, do you use homebridge UI? or only configuring in config file?
I do use the UI, and it puts the code in the right place, but I neede to update it manually after.

So my config looks like this:

        {
            "accessory": "Twinkly",
            "name": "Twinkly",
            "ip": "x.x.x.x",
            "allowBrightnessControl": true
        }

**Comment by bmpreston** [comment]
So my initial config had bridge: ... in it. If I kept that it gave me an
error. I think the bridge: ... should have code in it, no clue what.  Could
you send your complete file?

Appreciated.

**Comment by PrimaryInc** [comment]
Hi, so in this link there is a demo config file:
https://github.com/homebridge/homebridge/blob/master/config-sample.json

I guess I need to understand a bit more about you setup.
Windws, Linux?

**Comment by PrimaryInc** [comment]
Also look at this link:
https://github.com/homebridge/homebridge/blob/master/README.md

**Comment by bmpreston** [comment]
Good morning,

I'm actually out of bed and in front of my computer.  I am running
Windows.

Here is the default on start up.  I have uninstalled, reinstalled to get a
fresh config.  See the below screenshots as to how I set it up and the
error I am getting.

Thanks

[image: image.png]

[image: image.png]

[image: image.png]

**Comment by bmpreston** [comment]
![image](https://user-images.githubusercontent.com/29456939/100638675-49709c00-3302-11eb-8644-5e438857ed3c.png)

**Comment by PrimaryInc** [comment]
Hi,

Ok, it is a bit strange that you dont have Bridge config part in order.
Could you go to path:
C:\Users\"user you installed homebridge with"\.homebridge\persist
And see if there is any files under here?

Just to clarify you followed this guide?
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

**Comment by bmpreston** [comment]
@PrimaryInc 

I do not recall if I did or did not follow that guide.  I most certainly assume I did.  I've been running Homebridge for several months, running Ring, Wemo, Nest and others.  

Under the \persist path, I have these...

![image](https://user-images.githubusercontent.com/29456939/100653022-c6f1d780-3315-11eb-8d7a-4f4d6fb37919.png)

**Comment by PrimaryInc** [comment]
@bmpreston, 

If you used HB for a long time is this a error that just happened or a new installation?

If New:
So you config file should then start with:

{
    "bridge": {
        "name": "HomeBridge",
        "username": "0E:CE:45:74:E0:73",
        "port": 52540,
        "pin": "123-45-678"
    },

Just to explain username is the same as the "file" name.
Port is default
Pin - set what you want in that format.
If above works I'm happy, but not sure it it will. Im just looking in my ovn system to verify my config.

If Old system that failed:
Go to HJB web UI -> config, choose button restore and find the last working config file to restore.

**Comment by bmpreston** [comment]
So, I just deleted the bridge part in the settings of the Twinkly settings.  I instead made the following the config in the settings:

I think I see that under config all of the bridge information is there.  Not needed in the settings of the twinkly npm instead.

{
    "accessory": "Twinkly",
    "name": "Twinkly",
    "ip": "10.0.0.187",
    "allowBrightnessControl": true
}


I rebooted Homebridge, I receive this error.

[11/30/2020, 4:30:46 PM] [Twinkly] Error: connect ETIMEDOUT 10.0.0.187:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ETIMEDOUT',
  code: 'ETIMEDOUT',
  syscall: 'connect',
  address: '10.0.0.187',
  port: 80
}
[11/30/2020, 4:30:46 PM] [Twinkly] Authentication failure

**Comment by PrimaryInc** [comment]
@bmpreston,

Okay.. Now I'm a bit lost. 
Perhaps me missunderstanding what you actually are configuring. 
If you remove twinkly config, does HomeBridge then start as normal?
Is it just when you add twinkly config error starts?

Under config of Twinkly via the plugin web ui, no bridge config is to be added.
It should look like this:
![twinkley03](https://user-images.githubusercontent.com/45151934/100669204-579fd600-335d-11eb-9c06-fd93ab8e7081.PNG)

Only add correct IP.

If you use a web browser and open url http://10.0.0.187 what response do you get?

Perhaps you should attach you complete HomeBridge config file, it might be a bit easierto understand where issue is.

**Comment by bmpreston** [comment]
I think we may be crossing wires here:

Homebridge runs 100% correctly.  Ring, Wemo, Nest, Sensibo all run correctly.  The Twinkly is the only plugin asking for settings in a config file, others are in options, textboxes, checkboxes, etc.

The complete Homebridge Config is here:

{
    "bridge": {
        "name": "Homebridge E073",
        "username": "0E:CE:45:74:E0:73",
        "port": 51413,
        "pin": "928-09-208"
    },
    "accessories": [
        {
            "accessory": "Twinkly",
            "name": "Twinkly",
            "ip": "10.0.0.187",
            "allowBrightnessControl": true
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "form",
            "theme": "auto",
            "tempUnits": "f",
            "lang": "auto",
            "platform": "config"
        },
        {
            "platform": "SensiboAC",
            "apiKey": "**SCRUBBED**",
            "disableFan": true,
            "disableDry": true,
            "enableSyncButton": true,
            "enableOccupancySensor": false,
            "enableClimateReactSwitch": false,
            "enableHistoryStorage": false,
            "externalHumiditySensor": false,
            "debug": false
        },
        {
            "platform": "Ring",
            "name": "Ring",
            "refreshToken": "**SCRUBBED**"
        },
        {
            "googleAuth": {
                "issueToken": "**SCRUBBED**",
                "cookies": "**SCRUBBED**"
            },
            "ffmpegCodec": "libx264",
            "options": {
                "streamQuality": 3,
                "alertCheckRate": 10,
                "alertCooldownRate": 180,
                "importantOnly": true,
                "motionDetection": true,
                "streamingSwitch": true,
                "chimeSwitch": true,
                "doorbellAlerts": true,
                "doorbellSwitch": true,
                "audioSwitch": true
            },
            "platform": "Nest-cam"
        },
        {
            "name": "Belkin WeMo",
            "platform": "BelkinWeMo"
        }
    ]
}

When I click on 'Settings' for the Twinkly, I get this window:

![image](https://user-images.githubusercontent.com/29456939/100669997-3bd00c00-332c-11eb-9476-0e0db89c20e8.png)


![image](https://user-images.githubusercontent.com/29456939/100670039-4b4f5500-332c-11eb-9052-ff7c3bf44aec.png)


This below, made be believe, I should be copying this into the settings window:

![image](https://user-images.githubusercontent.com/29456939/100670094-64f09c80-332c-11eb-93d6-c504a6cbedf9.png)


This is how it now looks, and I cannot access it with a webpage or ping it.

![image](https://user-images.githubusercontent.com/29456939/100670171-7fc31100-332c-11eb-8e7a-14f789b76eac.png)

And I think I may have found my problem.  The app has an IP address listed, however this must be last years IP as my Router shows it as 10.0.0.50, and I just set the IP as static.  I cannot ping nor access the website for it though.

**Comment by PrimaryInc** [comment]
@bmpreston,

Yes we are!! That was my understanding. No problem, my bad.

SO, you config file looks ok, I just ran it on a json validator.
I would try to change IP to what ever you router tell you twinkly uses, and add it config file to verify.

**Comment by bmpreston** [comment]
So. One step closer.

I can turn off the tree. HomeKit allegedly is turning the tree on however
it does not actually turn on my lights.

**Comment by bmpreston** [comment]
This error is just as of last night when I downloaded and installed
Twinkly. Everything else does work and continues to work. In fact, logging
in last night I had several upgrades to process.

I will review your config files in a moment.

Thanks

**Comment by PrimaryInc** [comment]
@bmpreston,

Did you get any further?

**Comment by bmpreston** [comment]
Yes, I did.

It’s been a busy few weeks. Apologies on not getting back to you. This can
be closed.

It turns out that the system was setting brightness to 0 at random times.
It was on, just off. ;-)


Thank you for all your help!  Wonderful to have in HomeKit.

**Comment by PrimaryInc** [comment]
@bmpreston,

Great news :)
I cannot close case, but you should see a button for it on this page :)
