### ISSUE TITLE
Does not light up except when playing with the brightness

### ISSUE THREAD

**Issue by iDreamsX** [nschum/homebridge-twinkly#9]
Hello,

I have a problem with my twinkly garland and your plugin.

The configuration is going well, I can turn it off but can’t turn it on again directly. I have to use the brightness level if I want to turn it on again.

I have the second generation of garland, the TWS250STP-BFR

Please, could you look at if it is not a bug, it is really useful especially during the holidays.

Sorry if it’s mistranslated, I’m French and not very strong in English. 

I wanted to add that the firmware version is 2.5.6, I don't know if it can help you.

Thanks

**Comment by iDreamsX** [comment]
Sorry if it’s mistranslated, I’m French and not very strong in English. 

I wanted to add that the firmware version is 2.5.6, I don't know if it can help you.

**Comment by nschum** [comment]
I think this is the same as #4. Please report back how the new version works.
